# Generated by Django 5.0.3 on 2024-03-13 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_be_used_for', models.ManyToManyField(related_name='item_muscles', to='workout.muscles')),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')], default=1, max_length=6)),
                ('description', models.TextField(default='No description')),
                ('instruction', models.TextField(default='No instruction, be carefully')),
                ('number_of_sets', models.IntegerField(blank=True, null=True)),
                ('number_of_reps', models.IntegerField(blank=True, null=True)),
                ('avg_time', models.IntegerField(blank=True, help_text='average time for exercise in minutes', null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workout.items')),
                ('target_muscle', models.ManyToManyField(related_name='target_muscle', to='workout.muscles')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['level'],
            },
        ),
    ]
